openapi: 3.0.0
info:
  title: Event Burst Events API
  description: API documentation for legendary-octo-events
  version: 1.0.0
servers:
  - url: http://localhost:8003
  
components:
  schemas:
    Attendee:
      type: object
      properties:
        _id:
          type: string
          description: The unique identifier of the attendee.
        name:
          type: string
          description: The name of the attendee.
        email:
          type: string
          description: The email address of the attendee.
        phoneNumber:
          type: string
          description: The phone number of the attendee.
        address:
          type: string
          description: The address of the attendee.
        password:
          type: string
          description: The password of the attendee.
        refreshToken:
          type: string
          description: The refresh token of the attendee.
      required:
        - name
        - email
        - phoneNumber
        - address
        - password
