openapi: 3.0.0
info:
  title: Event Burst Events API
  description: API documentation for legendary-octo-events
  version: 1.0.0
servers:
  - url: http://localhost:8003

paths:
  /api/shiny-barnacle/attendee/get-all:
    get:
      summary: Get all attendees
      description: Retrieve a list of all attendees.
      tags:
        - Attendee
      responses:
        "200":
          description: A list of all attendees

  /api/shiny-barnacle/attendee/create:
    post:
      summary: Register a new attendee
      description: Register a new attendee in the system.
      tags:
        - Attendee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Attendee"
      responses:
        "200":
          description: Attendee registered successfully

  /api/shiny-barnacle/attendee/login:
    post:
      summary: Login as an attendee
      description: Authenticate as an attendee.
      tags:
        - Attendee
      responses:
        "200":
          description: Attendee logged in successfully

  /api/shiny-barnacle/attendee/refresh-token:
    post:
      summary: Refresh access token
      description: Refresh the access token using the refresh token.
      tags:
        - Attendee
      responses:
        "200":
          description: Access token refreshed successfully

  /api/shiny-barnacle/attendee/buy-ticket/{eventId}:
    post:
      summary: Buy a ticket
      description: Purchase a ticket for the specified event.
      tags:
        - Attendee
      parameters:
        - in: path
          name: eventId
          required: true
          schema:
            type: string
          description: ID of the event to buy a ticket for
      responses:
        "200":
          description: Ticket purchased successfully
        "401":
          description: Unauthorized - JWT token is missing or invalid

components:
  schemas:
    Attendee:
      type: object
      properties:
        _id:
          type: string
          description: The unique identifier of the attendee.
        name:
          type: string
          description: The name of the attendee.
        email:
          type: string
          description: The email address of the attendee.
        phoneNumber:
          type: string
          description: The phone number of the attendee.
        address:
          type: string
          description: The address of the attendee.
        password:
          type: string
          description: The password of the attendee.
        refreshToken:
          type: string
          description: The refresh token of the attendee.
      required:
        - name
        - email
        - phoneNumber
        - address
        - password
